In [ ]:
import numpy as np
import pandas as pd
array_2d = np.random.randint(50,100,size=(50,5))
df1 = pd.DataFrame(array_2d,
             columns=['國文','英文','數學','地理','社會'],
             index = [f'{num}號' for num in range(1,51)]
             )
df1

In [5]:
total_se = df1['國文'] + df1['英文'] + df1['數學'] + df1['地理'] + df1['社會']

In [ ]:
average_se = total_se / 5
average_se

In [7]:
df1['總分']=total_se #新增欄位
df1['平均']=average_se # 新增欄位
df1

     國文  英文  數學  地理  社會   總分    平均
1號   74  56  92  87  62  371  74.2
2號   95  66  93  95  97  446  89.2
3號   81  56  69  88  52  346  69.2
4號   86  58  98  58  89  389  77.8
5號   60  73  90  85  89  397  79.4
6號   82  97  87  77  51  394  78.8
7號   70  76  55  74  73  348  69.6
8號   82  55  56  84  88  365  73.0
9號   88  70  90  62  84  394  78.8
10號  98  94  93  66  61  412  82.4
11號  82  61  83  71  64  361  72.2
12號  94  63  86  99  92  434  86.8
13號  85  84  56  78  67  370  74.0
14號  68  71  52  52  72  315  63.0
15號  71  99  53  98  51  372  74.4
16號  59  77  82  58  71  347  69.4
17號  77  53  77  68  72  347  69.4
18號  56  70  93  61  86  366  73.2
19號  92  99  95  53  63  402  80.4
20號  70  52  54  69  77  322  64.4
21號  83  61  81  93  85  403  80.6
22號  89  57  51  67  53  317  63.4
23號  77  80  95  86  79  417  83.4
24號  68  96  69  52  78  363  72.6
25號  89  96  69  65  68  387  77.4
26號  81  64  91  67  52  355  71.0
27號  90  90  54  56  59  349  69.8
28號  93  73  83  78  67  394  78.8
29號  79  97  62  61  91  390  78.0
30號  58  89  50  51  98  346  69.2
31號  65  76  70  70  85  366  73.2
32號  67  52  70  52  96  337  67.4
33號  75  90  72  73  67  377  75.4
34號  68  54  69  93  64  348  69.6
35號  74  80  98  84  70  406  81.2
36號  96  58  51  84  60  349  69.8
37號  50  65  60  70  61  306  61.2
38號  91  85  70  98  63  407  81.4
39號  85  90  63  96  76  410  82.0
40號  56  71  77  98  57  359  71.8
41號  60  69  57  74  95  355  71.0
42號  90  76  96  67  68  397  79.4
43號  82  76  84  86  89  417  83.4
44號  64  57  59  54  58  292  58.4
45號  82  91  73  75  90  411  82.2
46號  91  62  55  69  51  328  65.6
47號  72  71  98  65  79  385  77.0
48號  91  59  73  59  93  375  75.0
49號  82  86  86  99  84  437  87.4
50號  81  77  63  78  86  385  77.0

In [ ]:
##Series使用比較運算子
df1['總分'] >= 400

In [ ]:
#dataFrame使用subscript,搜尋資料
#dataFrame[bool Series]
#True的保留,Flase的消除
df1[df1['總分'] >= 400]

In [9]:
#查詢國文95分以上的學生
df1[df1['國文']>=95]

     國文  英文  數學  地理  社會   總分    平均
2號   95  66  93  95  97  446  89.2
10號  98  94  93  66  61  412  82.4
36號  96  58  51  84  60  349  69.8

In [15]:
#查詢國文95分以上的學生同時總分400分以上
#and = & ,()-->優先運算子
#or = |
df1[(df1['國文']>=95) & (df1['總分']>=400)]

     國文  英文  數學  地理  社會   總分    平均
2號   95  66  93  95  97  446  89.2
10號  98  94  93  66  61  412  82.4

In [16]:
df1[(df1['國文']>=95) | (df1['總分']>=400)]

     國文  英文  數學  地理  社會   總分    平均
2號   95  66  93  95  97  446  89.2
10號  98  94  93  66  61  412  82.4
12號  94  63  86  99  92  434  86.8
19號  92  99  95  53  63  402  80.4
21號  83  61  81  93  85  403  80.6
23號  77  80  95  86  79  417  83.4
35號  74  80  98  84  70  406  81.2
36號  96  58  51  84  60  349  69.8
38號  91  85  70  98  63  407  81.4
39號  85  90  63  96  76  410  82.0
43號  82  76  84  86  89  417  83.4
45號  82  91  73  75  90  411  82.2
49號  82  86  86  99  84  437  87.4