In [3]:
import numpy as np
import pandas as pd

scores=pd.DataFrame(np.random.randint(50,101,size=(50,5)),
                    columns=['國文', '英文', '數學', '地理', '歷史'],
                    index=range(1,51))
scores

     國文  英文   數學  地理  歷史
1    89  60   99  89  88
2    97  64   94  85  96
3    93  59   91  74  88
4    86  66  100  69  70
5    77  79   87  58  73
6    87  99   85  87  93
7    94  71   56  53  67
8    97  77   65  87  51
9    99  85   73  94  90
10   50  83   66  62  69
11   97  76   58  69  61
12   79  95   56  74  63
13   52  69   51  71  90
14   76  59   75  81  99
15   52  82   88  50  82
16   88  90   73  74  57
17   98  88   72  73  99
18   60  92  100  56  56
19   67  89   58  91  96
20   84  77   71  99  94
21   80  80   52  83  97
22   75  84   85  53  94
23   82  53   77  76  78
24   99  54   65  96  56
25   73  63   72  98  65
26   92  82   91  87  54
27   59  65   61  59  95
28   88  96   61  63  55
29   54  97   65  78  95
30   90  53   99  87  92
31   62  66   95  77  67
32   63  78   70  64  74
33   86  87   77  67  93
34   53  59   99  89  53
35   85  62   63  98  67
36   98  74   73  51  85
37   80  87   95  72  94
38  100  59   66  77  59
39   86  58   68  74  60
40   55  65   85  76  55
41   85  76   75  55  91
42   95  54   94  80  61
43   99  71   88  93  87
44   89  95   89  58  66
45   92  51   69  84  94
46   69  70   54  79  85
47   84  85   74  72  64
48   56  68   99  98  51
49   52  96   81  64  80
50   72  98   66  96  91

In [4]:
#lambda 匿名函式，是在電腦的編碼過程中，不需要定義函式名稱的一種函式。目前這種函式已經普遍的存在多種程式語言中。在Python中所謂Lambda函式，也就是匿名函式。
#函式本身可以接收多個參數並且返回ㄧ個表達式的值。其中func是指定的名稱，也可以沒有。
#沿 DataFrame 的軸應用函數。

scores.apply(lambda item:print(item))
#DataFrame.apply(func, axis=0, raw=False, result_type=None, args=()....
#apply內要放一個funw它就會沿著 DataFrame 的軸去應用函數,並用serise的方式回傳給我們。

1      89
2      97
3      93
4      86
5      77
6      87
7      94
8      97
9      99
10     50
11     97
12     79
13     52
14     76
15     52
16     88
17     98
18     60
19     67
20     84
21     80
22     75
23     82
24     99
25     73
26     92
27     59
28     88
29     54
30     90
31     62
32     63
33     86
34     53
35     85
36     98
37     80
38    100
39     86
40     55
41     85
42     95
43     99
44     89
45     92
46     69
47     84
48     56
49     52
50     72
Name: 國文, dtype: int64
1     60
2     64
3     59
4     66
5     79
6     99
7     71
8     77
9     85
10    83
11    76
12    95
13    69
14    59
15    82
16    90
17    88
18    92
19    89
20    77
21    80
22    84
23    53
24    54
25    63
26    82
27    65
28    96
29    97
30    53
31    66
32    78
33    87
34    59
35    62
36    74
37    87
38    59
39    58
40    65
41    76
42    54
43    71
44    95
45    51
46    70
47    85
48    68
49    96
50    98
Name: 英文, dtype: int64
1      99
2      94
3      91
4     100
5      87
6      85
7      56
8      65
9      73
10     66
11     58
12     56
13     51
14     75
15     88
16     73
17     72
18    100
19     58
20     71
21     52
22     85
23     77
24     65
25     72
26     91
27     61
28     61
29     65
30     99
31     95
32     70
33     77
34     99
35     63
36     73
37     95
38     66
39     68
40     85
41     75
42     94
43     88
44     89
45     69
46     54
47     74
48     99
49     81
50     66
Name: 數學, dtype: int64
1     89
2     85
3     74
4     69
5     58
6     87
7     53
8     87
9     94
10    62
11    69
12    74
13    71
14    81
15    50
16    74
17    73
18    56
19    91
20    99
21    83
22    53
23    76
24    96
25    98
26    87
27    59
28    63
29    78
30    87
31    77
32    64
33    67
34    89
35    98
36    51
37    72
38    77
39    74
40    76
41    55
42    80
43    93
44    58
45    84
46    79
47    72
48    98
49    64
50    96
Name: 地理, dtype: int64
1     88
2     96
3     88
4     70
5     73
6     93
7     67
8     51
9     90
10    69
11    61
12    63
13    90
14    99
15    82
16    57
17    99
18    56
19    96
20    94
21    97
22    94
23    78
24    56
25    65
26    54
27    95
28    55
29    95
30    92
31    67
32    74
33    93
34    53
35    67
36    85
37    94
38    59
39    60
40    55
41    91
42    61
43    87
44    66
45    94
46    85
47    64
48    51
49    80
50    91
Name: 歷史, dtype: int64

國文    None
英文    None
數學    None
地理    None
歷史    None
dtype: object

In [5]:
def abc(s):
    return s.max()
scores.apply(abc)

#最大只有一個值

國文    100
英文     99
數學    100
地理     99
歷史     99
dtype: int64

In [6]:
def abc(s):
    return pd.Series([s.max(),s.min(),s.mean()],index=['最高分','最低分','平均'])
scores.apply(abc)

#每個值分別輸出後都是series的形式，組合起來後會變成Dataframe的形式。

        國文     英文      數學    地理    歷史
最高分  100.0  99.00  100.00  99.0  99.0
最低分   50.0  51.00   51.00  50.0  51.0
平均    79.5  74.92   76.52  76.0  76.8

In [13]:
scores.index = scores.index.map(lambda i:f'{i}號')
scores.index = scores.index.str.replace(r'號+', '號', regex=True)
scores

      國文  英文   數學  地理  歷史
1號    89  60   99  89  88
2號    97  64   94  85  96
3號    93  59   91  74  88
4號    86  66  100  69  70
5號    77  79   87  58  73
6號    87  99   85  87  93
7號    94  71   56  53  67
8號    97  77   65  87  51
9號    99  85   73  94  90
10號   50  83   66  62  69
11號   97  76   58  69  61
12號   79  95   56  74  63
13號   52  69   51  71  90
14號   76  59   75  81  99
15號   52  82   88  50  82
16號   88  90   73  74  57
17號   98  88   72  73  99
18號   60  92  100  56  56
19號   67  89   58  91  96
20號   84  77   71  99  94
21號   80  80   52  83  97
22號   75  84   85  53  94
23號   82  53   77  76  78
24號   99  54   65  96  56
25號   73  63   72  98  65
26號   92  82   91  87  54
27號   59  65   61  59  95
28號   88  96   61  63  55
29號   54  97   65  78  95
30號   90  53   99  87  92
31號   62  66   95  77  67
32號   63  78   70  64  74
33號   86  87   77  67  93
34號   53  59   99  89  53
35號   85  62   63  98  67
36號   98  74   73  51  85
37號   80  87   95  72  94
38號  100  59   66  77  59
39號   86  58   68  74  60
40號   55  65   85  76  55
41號   85  76   75  55  91
42號   95  54   94  80  61
43號   99  71   88  93  87
44號   89  95   89  58  66
45號   92  51   69  84  94
46號   69  70   54  79  85
47號   84  85   74  72  64
48號   56  68   99  98  51
49號   52  96   81  64  80
50號   72  98   66  96  91

In [24]:
def abc1(item):
    return pd.Series([item.sum(),item.mean()],index=['總分','平均'])
scores.apply(abc1,axis=1)

        總分    平均
1號   425.0  85.0
2號   436.0  87.2
3號   405.0  81.0
4號   391.0  78.2
5號   374.0  74.8
6號   451.0  90.2
7號   341.0  68.2
8號   377.0  75.4
9號   441.0  88.2
10號  330.0  66.0
11號  361.0  72.2
12號  367.0  73.4
13號  333.0  66.6
14號  390.0  78.0
15號  354.0  70.8
16號  382.0  76.4
17號  430.0  86.0
18號  364.0  72.8
19號  401.0  80.2
20號  425.0  85.0
21號  392.0  78.4
22號  391.0  78.2
23號  366.0  73.2
24號  370.0  74.0
25號  371.0  74.2
26號  406.0  81.2
27號  339.0  67.8
28號  363.0  72.6
29號  389.0  77.8
30號  421.0  84.2
31號  367.0  73.4
32號  349.0  69.8
33號  410.0  82.0
34號  353.0  70.6
35號  375.0  75.0
36號  381.0  76.2
37號  428.0  85.6
38號  361.0  72.2
39號  346.0  69.2
40號  336.0  67.2
41號  382.0  76.4
42號  384.0  76.8
43號  438.0  87.6
44號  397.0  79.4
45號  390.0  78.0
46號  357.0  71.4
47號  379.0  75.8
48號  372.0  74.4
49號  373.0  74.6
50號  423.0  84.6

In [20]:
one_student = scores.iloc[2]
less_student = one_student[one_student < 60]
less_student

英文    59
Name: 3號, dtype: int64

In [21]:
less_student.count()
",".join(less_student.index.values.tolist())

'英文'

In [22]:
less_student.count()
less_student_1=less_student.index
less_student_1

Index(['英文'], dtype='object')

In [23]:
#重新定義function
def abc1(item):
    less_student=item[item<60]
    less_count=less_student.count()
    less_str = ",".join(less_student.index.values.tolist())
    
    return pd.Series([item.sum(),item.mean(),less_count,less_str],index=['總分','平均','不及格科目數','不及格科目'])
scores.apply(abc1,axis=1)
#利用apply 針對每一列進行分析並得到總分、平均、不及格科目數,不及格科目

      總分    平均  不及格科目數     不及格科目
1號   425  85.0       0
2號   436  87.2       0
3號   405  81.0       1        英文
4號   391  78.2       0
5號   374  74.8       1        地理
6號   451  90.2       0
7號   341  68.2       2     數學,地理
8號   377  75.4       1        歷史
9號   441  88.2       0
10號  330  66.0       1        國文
11號  361  72.2       1        數學
12號  367  73.4       1        數學
13號  333  66.6       2     國文,數學
14號  390  78.0       1        英文
15號  354  70.8       2     國文,地理
16號  382  76.4       1        歷史
17號  430  86.0       0
18號  364  72.8       2     地理,歷史
19號  401  80.2       1        數學
20號  425  85.0       0
21號  392  78.4       1        數學
22號  391  78.2       1        地理
23號  366  73.2       1        英文
24號  370  74.0       2     英文,歷史
25號  371  74.2       0
26號  406  81.2       1        歷史
27號  339  67.8       2     國文,地理
28號  363  72.6       1        歷史
29號  389  77.8       1        國文
30號  421  84.2       1        英文
31號  367  73.4       0
32號  349  69.8       0
33號  410  82.0       0
34號  353  70.6       3  國文,英文,歷史
35號  375  75.0       0
36號  381  76.2       1        地理
37號  428  85.6       0
38號  361  72.2       2     英文,歷史
39號  346  69.2       1        英文
40號  336  67.2       2     國文,歷史
41號  382  76.4       1        地理
42號  384  76.8       1        英文
43號  438  87.6       0
44號  397  79.4       1        地理
45號  390  78.0       1        英文
46號  357  71.4       1        數學
47號  379  75.8       0
48號  372  74.4       2     國文,歷史
49號  373  74.6       1        國文
50號  423  84.6       0